In [1]:
print('Numpy First Class')

Numpy First Class


In [2]:
a=[1,2,3,4,5]
print([i**2 for i in a])

[1, 4, 9, 16, 25]


In [3]:
import numpy as np

In [4]:
b=np.array([1,2,3,4,5])

In [5]:
b

array([1, 2, 3, 4, 5])

In [6]:
b**2

array([ 1,  4,  9, 16, 25])

In [7]:
l = range(100000)
l

range(0, 100000)

In [8]:
%timeit [i**2 for i in l]

14.9 ms ± 29.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
k = np.array(range(100000))
k

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [10]:
%timeit k**2

24.4 µs ± 246 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
p= np.array([1,2,3,4.5])
p

array([1. , 2. , 3. , 4.5])

In [12]:
q=np.array([1,2,3,4,'A'])
q

array(['1', '2', '3', '4', 'A'], dtype='<U21')

In [13]:
a= np.array([1,2,3,4,5])
a.ndim

1

In [14]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b.ndim

2

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a.shape

(5,)

In [17]:
b.shape

(3, 3)

In [18]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
b.ndim

2

In [20]:
b.shape

(2, 3)

In [21]:
type(b)

numpy.ndarray

In [22]:
b.dtype

dtype('int64')

In [23]:
a= np.array([1,2,3,4,'a'])
a

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [24]:
a.dtype

dtype('<U21')

In [25]:
l=np.arange(10)
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
l=np.arange(5,10)
l

array([5, 6, 7, 8, 9])

In [27]:
l=np.arange(5,30,3)
l

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [28]:
l=np.arange(5,10,.2)
l

array([5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4,
       7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [29]:
a =np.arange(1,12)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
a[:4]

array([1, 2, 3, 4])

In [31]:
a[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [32]:
a[2:8:2]

array([3, 5, 7])

In [33]:
a[:-5:-1]

array([11, 10,  9,  8])

In [34]:
a[-5:-2:1]

array([7, 8, 9])

In [35]:
a[-2:-9:-2]

array([10,  8,  6,  4])

# second class


In [36]:
a= np.arange(1,12)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a[:4] =13
a

array([13, 13, 13, 13,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a=np.array([1,2,3,4,5])
b=np.array([8,7,6])
a[2:] = b[::-1]

In [39]:
a

array([1, 2, 6, 7, 8])

In [40]:
a= np.array([1,2,3,4,5,6,7,8,9])
a[3:] = 100
a

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

### Masking

In [41]:
a= np.arange(12)

In [42]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
mask = a<6

In [44]:
a[mask]

array([0, 1, 2, 3, 4, 5])

In [45]:
mask = a%2==0

In [46]:
a[mask]

array([ 0,  2,  4,  6,  8, 10])

In [47]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
mask1= a%2==0
mask2= a%5==0

In [49]:
a[mask1]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
a[mask2]

array([ 0,  5, 10, 15])

In [51]:
a[mask1 | mask2]

array([ 0,  2,  4,  5,  6,  8, 10, 12, 14, 15, 16, 18])

In [52]:
a[mask1 & mask2]

array([ 0, 10])

In [53]:
a=np.arange(4)
a

array([0, 1, 2, 3])

In [54]:
a+3

array([3, 4, 5, 6])

In [55]:
np.add(a,2)

array([2, 3, 4, 5])

In [56]:
np.sum(a)

6

In [57]:
np.min(a)

0

In [58]:
np.max(a)

3

In [59]:
a.sum()

6

In [60]:
np.mean(a)

1.5

In [61]:
a.mean()

1.5

In [62]:
a.min()

0

In [63]:
a.max()

3

## AirBNB Data

In [64]:
#https://drive.google.com/file/d/14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8/view?usp=sharing

In [65]:
!gdown 14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8

Downloading...
From: https://drive.google.com/uc?id=14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8
To: /Users/sivakumar/Desktop/Numpy/survey.txt
100%|██████████████████████████████████████| 2.55k/2.55k [00:00<00:00, 5.18MB/s]


In [66]:
!pip install gdown

In [67]:
!pip install --upgrade pip

In [68]:
score=np.loadtxt('/Users/sivakumar/Desktop/Numpy/survey.txt', dtype=int)

In [69]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [70]:
score.shape

(1167,)

In [71]:
score.min()

1

In [72]:
score.max()

10

In [73]:
detractors_mask = (score<=6)
detractors_mask

array([False, False,  True, ...,  True, False, False])

In [75]:
detractors = score[detractors_mask]
detractors.shape

(332,)

In [80]:
detractors_num= detractors.shape[0]
detractors_num

332

In [77]:
promoters_mask = (score>=9)
promoters_mask

array([False,  True, False, ..., False,  True,  True])

In [78]:
promoters = score[promoters_mask]
promoters.shape

(609,)

In [81]:
promoters_num= promoters.shape[0]
promoters_num

609

In [82]:
total = score.shape[0]
total

1167

In [84]:
detractors_percentage = detractors_num/total * 100
detractors_percentage

28.449014567266495

In [85]:
promoters_percentage = promoters_num/total * 100
promoters_percentage

52.185089974293064

In [86]:
nps= promoters_percentage-detractors_percentage
nps

23.73607540702657

Ours is a Good Score NPS